### ISSUE TITLE
Quick question about input format of base and tuned models

### ISSUE THREAD

**Issue by chujiezheng** [Re-Align/URIAL#1]
Thanks for your great work! I have a quick question about the input format of the base model and the tuned model, such as llama-2 vs. llama-2-chat. Concretely, llama-2-chat uses sequences like `[INST]`, `[/INST]`, `<<<SYS>>>` and `<<</SYS>>>` to distinguish the system prompt and user/assistant utterances. See [[1]](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/blob/c1b0db933684edbfe29a06fa47eb19cc48025e93/tokenizer_config.json#L12), [[2]](https://github.com/huggingface/transformers/blob/acd653164b6874e395ac9d46850f67599d8cdb58/src/transformers/models/llama/tokenization_llama.py#L53), while I think llama-2 may not understand these texts if directly prompted with the same format. So I wonder about the specific input formats of llama-2 and llama-2-chat (and if possible, other base/tuned models).

**Comment by yuchenlin** [comment]
Hi Chujie, 

Thanks for the great question. We use the zero-shot prompting template for untuned llm and use the official template (as you mentioned) for the aligned LLMs. These details are shown in Appendix C on Page 23. And you can also use this web demos to see the concrete prefixes used for base and aligned LLMs: https://allenai.github.io/re-align/tds/llama2/

For example, if you click the token `artists`, then you can see the two prefixes which are used for inputing base and aligned LLMs respectively. 

![image](https://github.com/Re-Align/URIAL/assets/10104354/5201635c-d30e-4ffd-b94d-c7ec3fc3eb15)


I hope this answers your question! Thanks!

Best,
Yuchen

**Comment by chujiezheng** [comment]
Thanks for your reply. It resolves my question!
