### ISSUE TITLE
Scripts for experiments on "ALIGNMENT AS TOKEN DISTRIBUTION SHIFT"

### ISSUE THREAD

**Issue by Sreyan88** [Re-Align/URIAL#2]
Hello!

Great work. Do you plan on releasing the code for the analysis you do in your paper in the subsection "ALIGNMENT AS TOKEN DISTRIBUTION SHIFT"? Thank You!

**Comment by Sreyan88** [comment]
Thank You! Looking forward!

**Comment by Sreyan88** [comment]
Hi @yuchenlin,

I am trying to replicate some of your analysis with different combinations of LLMs and training datasets, while you are getting your code ready. However, I am not sure how in the huggingface model.generate() function one can return a list of top-k tokens at each step of decoding. Can you please help me with this?

Thank You!

**Comment by yuchenlin** [comment]
Hey @Sreyan88,

I uploaded a (very rough) version of the code about token distribution analysis here: https://github.com/Re-Align/AlignTDS

Would u plz take a look?  (I haven't got time to make better documentation and testing yet, so please be prepared that there might be a few minor bugs). 

Best,
Yuchen

**Comment by Sreyan88** [comment]
Hi @yuchenlin ,

Thank You so much for the scripts! Had a look and looks promising! Again, great work!
