### ISSUE TITLE
Simple prompt template for URIAL?

### ISSUE THREAD

**Issue by jamesbraza** [Re-Align/URIAL#4]
Hello URIAL creators, I am looking to understand URIAL and am having tough time from the [paper](https://arxiv.org/abs/2312.01552) alone.

Are there any of the following available in this repo:

- A LangChain style `PromptTemplate`
- An example full-length chat (or just context) involving URIAL

**Comment by yuchenlin** [comment]
we don't support langchain but you can see a open-source demo here for a better understanding of URIAL:

https://huggingface.co/spaces/allenai/BaseChat_URIAL

**Comment by jamesbraza** [comment]
Awesome, thank you @yuchenlin ! Going to close this out
