### ISSUE TITLE
Are these results from URIAL Bench?

### ISSUE THREAD

**Issue by zhimin-z** [Re-Align/URIAL#7]
<img width="544" alt="image" src="https://github.com/Re-Align/URIAL/assets/8592144/464a24ba-138f-4fd2-8dcc-4a78118efea8">

**Comment by yuchenlin** [comment]
yes, check out the bench gradio here: https://huggingface.co/spaces/allenai/URIAL-Bench

**Comment by zhimin-z** [comment]
> yes, check out the bench gradio here: https://huggingface.co/spaces/allenai/URIAL-Bench

Thanks for your reply. Thus URIAL Bench and URIAL-MT Bench are basically the same benchmark?

**Comment by yuchenlin** [comment]
yes the same thing. sorry for the confusion. but we'll do an update soon to replace MT-bench with our own WildBench-v2's data --> https://huggingface.co/spaces/allenai/WildBench
